import React from "react";

export const Privacy = () => {
  return (
    <div className="max-w-3xl mx-auto py-12 px-4 sm:py-16 sm:px-6 lg:px-8">
      <h2 className="text-2xl font-extrabold tracking-tight text-gray-900 sm:text-3xl">
        Privacy Policy
      </h2>
      <p className="mt-6 max-w-2xl text-xl text-gray-500">
        This Privacy Policy describes how TechNessie (“we,” “us,” or “our”)
        collects, uses, and shares information about you when you use our
        website katiekickscancer.com (the “Site”).
      </p>

      <h3 className="text-lg leading-6 font-medium text-gray-900 mt-8">
        1. Information We Collect
      </h3>
      <p className="mt-4 max-w-2xl text-md text-gray-500">
        Email addresses: We may collect your email address only when you provide it
        to us, for example, when you sign up for the newsletter. We will not
        share your email address with third parties. We may use your email
        address to communicate with you about our products, services, or
        promotions. You may choose to unsubscribe from our emails at any time by
        clicking the "unsubscribe" link at the bottom of our emails.
      </p>

      <h3 className="text-lg leading-6 font-medium text-gray-900 mt-8">
        2. How We Use Your Information
      </h3>
      <p className="mt-4 max-w-2xl text-md text-gray-500">
        As we do not collect any personal information through the Site, we do
        not use your information in any way.
      </p>

      <h3 className="text-lg leading-6 font-medium text-gray-900 mt-8">
        3. Information Sharing
      </h3>
      <p className="mt-4 max-w-2xl text-md text-gray-500">
        We do not share any information with third parties.
      </p>

      <h3 className="text-lg leading-6 font-medium text-gray-900 mt-8">
        4. Security
      </h3>
      <p className="mt-4 max-w-2xl text-md text-gray-500">
        We take reasonable measures to help protect information about you from
        loss, theft, misuse and unauthorized access, disclosure, alteration, and
        destruction.
      </p>

      <h3 className="text-lg leading-6 font-medium text-gray-900 mt-8">
        5. Changes to this Policy
      </h3>
      <p className="mt-4 max-w-2xl text-md text-gray-500">
        We may modify this Privacy Policy at any time. If we make material
        changes to this Privacy Policy, we will notify you by updating the date
        of this Privacy Policy and posting it on the Site. We may also provide
        notification of changes in another way that we believe is reasonably
        likely to reach you, such as via e-mail (if you have provided your
        e-mail address).
      </p>

      <h3 className="text-lg leading-6 font-medium text-gray-900 mt-8">
        6. Contact Us
      </h3>
      <p className="mt-4 max-w-2xl text-md text-gray-500">
        If you have any questions or concerns about this Privacy Policy or our
        practices, please contact us at contact@technessie.com.
      </p>

      <h3 className="text-lg leading-6 font-medium text-gray-900 mt-8">
      7. Use of Google Analytics
      </h3>
      <p className="mt-4 max-w-2xl text-md text-gray-500 mb-10">
        We use Google Analytics, a web analysis service of Google Inc. ("Google"), to improve the user experience on our website such as informing us about % of use via mobile or desktop for example. These insights help us improved the experience and design of the site for users. Other engagements such as clicks or page views to help us learn which resources are most helpful to users. Google Analytics uses cookies to help us analyze these interactions, compile reports on the Site’s activity, and provide other services related to Site activity and usage.
        The information generated by the cookie about your use of the Site may be transmitted to and stored by Google on servers in the United States. Google may also transfer this information to third parties where required to do so by law.
        To opt-out of Google Analytics, you can download and install the Google Analytics Opt-out Browser Add-on for your web browser. This Add-on prevents the Google Analytics JavaScript running on websites from sharing information with Google Analytics about visit activity.
        For more information on Google's privacy practices and how it uses Google Analytics data, please visit Google's Privacy & Terms.
        </p>
    </div>
  );
};

export default Privacy;
